before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - bash ./scripts/validate-tests.sh
install:
  - yarn
after_success:
  - bash ./scripts/docs-upload-gh.sh
branches:
  only:
  - master
  - /^release\\/.*$/
env:
  global:
    - secure: "Recue3+sPDb4kQtKftZuYa0zwg6/+H+QO5tJP8WGa+Xq7OZBGzAt/bADW0Q7KvUPxtK6qUCynuWrnaBlEWc+UKIHlrcHCpFPn0zkpzGvzX6a+tvhjHAQNDB7x/VYORvYEQqMzWC5t+qLj6C9ffjXP+6uCo+o+y/5K5ydEyqa2e42LQblSJmiiCG754CqV1LxmasklGAC90+ldR6d7PFFpqXDc/BIsyDAIuS4FXfjyli+VnvCza7PQJ4XGkCoywmBNg8bcR82UwduA854/Gr7oYKZRUamMpBuQY25EupjwZ/GV2OyDSK3UcO3blEVrjRnP3gC9Ljd+WvcBqy7d1FJTCk0Vsy/pstxjVpP19H3I6xOU41buB3Pw1aLTkIp+PFmhoab5fu03bWfwUp/N1Xl1URKWcIKokwh/98NSA8OZ16VbMhFkxuUCs5bsFR+DB6SLdc2XNpzzdxdoe3XZHB5LxVOIoJY6CiskfYdNBPsEo+NZTrv+eUk+l4gMNTIYwgCWEbbIvXE6CwFITg9ERQhY7fvGJ37DOWfvLfxKnDc0jFqnlUnWgrtDppx7akE1vgfFu9W8jWRF4phGU/O4BwWUNhLtoGUgTH6RR4+4xoNv3LB1g6fnd50jUin4f6o2KSOkdPZFPmv74MygC7WyPERWR2IjpT2x+yfPIa6TetlY/c="
language: node_js
node_js:
  - "6"
cache:
  directories:
  - $HOME/.yarn-cache
addons:
  browserstack:
    username: "natanlafontaine1"
    access_key:
      secure: "Hg8TKFo0wgnPxQ1jhYmPMtwSeWF5sbQRa3bB0Ts9SkLOVmrhFx18QuA4or4B1JLDT1U1aC7E3xV3bbgsOhsTUx5Ww4FLK8AjVjAp3ut2dNmLOYMRNNbdD/62oKSPGK2R/GEE1F+C1QJi7GVUqYPda/ye0ab2N1RTZTYXuonmU/b0A1m/r07QGD1EhpBJ6Nt67eNwi8ReVKaH/sOV5SM1qw+aRjZsQFqE4eQx5QKB3Jvex5xWsKJTBMBYMHxvGA06lIkceLpsVswoH5NUyuJ3I94CJTfY7u6yXRhWiynPZeQiGwWYL4R45ahBQUNm4HhPyTne2vehYrsW/4n4OFpCOF7a1UaP4Gpx7W44GemSnAKax/w/JnMs1p25imhVLjzuLp3/UPVwUivJFXLm4AknVvX+RF0/vmlJpt/fLxjcu2u/+UbnUCPUO3W7BAKrY4yXidHmnlDGI8h4UZgElGvjCtcIken2kan1dxYTkvdfDqncma3LzeRcByCHk9NELNChkawozp32LQ98xVB5RPAM72abhofrFxYYijo8xvav5ssj0UG/CW4YMcOIji7mqjyOv1RFCNhEDJ5iFRxL/1+bEZN1vyS70VF0afNUdVfYa56PO9PUqlE0wZ53T126JvsLMayfXHtjqef6jM7ItTh1NwuqQkDQ/pMIYEkH5+VJU08="
